/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for an example event
 */
export interface Example {
  /**
   * A string property which is required in this schema
   */
  required_property: string;
  /**
   * A number property which is optional in this schema
   */
  optional_property?: number;
  /**
   * A string array property
   */
  array_property?: string[];
  /**
   * A string array property which must have at least one object
   */
  array_min_items_property?: [string, ...string[]];
  /**
   * A object property which can have string and boolean values
   */
  object_property?: {
    [k: string]: string | boolean;
  };
  /**
   * A string enum property which must be one of three values
   */
  enum_property?: "one" | "two" | "three";
  [k: string]: unknown;
}
